"""Shared typed tool registry for all service and agent entry points."""

from quanxin_life.tools.batch_decision import (
    BATCH_DECISION_TOOL_VERSION,
    BatchDecisionToolInput,
    execute_batch_decision_tool,
    register_batch_decision_tool,
)
from quanxin_life.tools.battery_evidence import (
    BATTERY_EVIDENCE_ARTIFACT_TYPE,
    BATTERY_EVIDENCE_RETRIEVAL_TOOL_VERSION,
    RetrieveBatteryEvidenceToolInput,
    execute_retrieve_battery_evidence_tool,
    register_retrieve_battery_evidence_tool,
)
from quanxin_life.tools.bootstrap import create_available_tool_registry
from quanxin_life.tools.data_quality import (
    DATA_QUALITY_MODEL_VERSION,
    DATA_QUALITY_TOOL_VERSION,
    ValidateBatteryDataToolInput,
    execute_validate_battery_data_tool,
    register_validate_battery_data_tool,
)
from quanxin_life.tools.mcp_adapter import (
    McpAdapterError,
    McpRequestValidationError,
    McpSdkUnavailableError,
    McpToolAdapter,
    McpToolCallRequest,
    load_optional_mcp_sdk,
)
from quanxin_life.tools.mcp_host import (
    McpHost,
    McpHostConfig,
    McpTransport,
    create_mcp_host,
    run_mcp_host,
)
from quanxin_life.tools.next_experiment_recommendation import (
    EXPERIMENT_RECOMMENDATION_EVIDENCE_TYPE,
    NEXT_EXPERIMENT_RECOMMENDATION_TOOL_VERSION,
    RecommendNextExperimentToolInput,
    execute_recommend_next_experiment_tool,
    register_recommend_next_experiment_tool,
)
from quanxin_life.tools.physics_check import (
    PHYSICS_CHECK_TOOL_VERSION,
    CheckOperatingConditionToolInput,
    execute_check_operating_condition_tool,
    register_check_operating_condition_tool,
)
from quanxin_life.tools.registry import (
    DuplicateToolError,
    RegisteredTool,
    StandardToolName,
    ToolAuthorizationError,
    ToolContractError,
    ToolDefinition,
    ToolExecutionError,
    ToolExecutionScope,
    ToolInputValidationError,
    ToolRegistry,
    ToolRegistryError,
    ToolSchema,
    UnknownToolError,
)
from quanxin_life.tools.scenario_lifetime import (
    SCENARIO_CONVERSION_WARNING,
    SCENARIO_LIFETIME_ARTIFACT_TYPE,
    SCENARIO_LIFETIME_TOOL_VERSION,
    ScenarioLifetimeToolInput,
    execute_scenario_lifetime_tool,
    register_scenario_lifetime_tool,
)
from quanxin_life.tools.split_audit import (
    SPLIT_AUDIT_MODEL_VERSION,
    SPLIT_AUDIT_TOOL_VERSION,
    AuditDatasetSplitToolInput,
    execute_audit_dataset_split_tool,
    register_audit_dataset_split_tool,
)
from quanxin_life.tools.target_domain_adaptation import (
    TARGET_DOMAIN_ADAPTATION_TOOL_VERSION,
    AdaptToTargetDomainToolInput,
    execute_adapt_to_target_domain_tool,
    register_adapt_to_target_domain_tool,
)

__all__ = [
    "BATCH_DECISION_TOOL_VERSION",
    "BATTERY_EVIDENCE_ARTIFACT_TYPE",
    "BATTERY_EVIDENCE_RETRIEVAL_TOOL_VERSION",
    "DATA_QUALITY_MODEL_VERSION",
    "DATA_QUALITY_TOOL_VERSION",
    "EXPERIMENT_RECOMMENDATION_EVIDENCE_TYPE",
    "NEXT_EXPERIMENT_RECOMMENDATION_TOOL_VERSION",
    "PHYSICS_CHECK_TOOL_VERSION",
    "SCENARIO_CONVERSION_WARNING",
    "SCENARIO_LIFETIME_ARTIFACT_TYPE",
    "SCENARIO_LIFETIME_TOOL_VERSION",
    "SPLIT_AUDIT_MODEL_VERSION",
    "SPLIT_AUDIT_TOOL_VERSION",
    "TARGET_DOMAIN_ADAPTATION_TOOL_VERSION",
    "AdaptToTargetDomainToolInput",
    "AuditDatasetSplitToolInput",
    "BatchDecisionToolInput",
    "CheckOperatingConditionToolInput",
    "DuplicateToolError",
    "McpAdapterError",
    "McpHost",
    "McpHostConfig",
    "McpRequestValidationError",
    "McpSdkUnavailableError",
    "McpToolAdapter",
    "McpToolCallRequest",
    "McpTransport",
    "RecommendNextExperimentToolInput",
    "RegisteredTool",
    "RetrieveBatteryEvidenceToolInput",
    "ScenarioLifetimeToolInput",
    "StandardToolName",
    "ToolAuthorizationError",
    "ToolContractError",
    "ToolDefinition",
    "ToolExecutionError",
    "ToolExecutionScope",
    "ToolInputValidationError",
    "ToolRegistry",
    "ToolRegistryError",
    "ToolSchema",
    "UnknownToolError",
    "ValidateBatteryDataToolInput",
    "create_available_tool_registry",
    "create_mcp_host",
    "execute_adapt_to_target_domain_tool",
    "execute_audit_dataset_split_tool",
    "execute_batch_decision_tool",
    "execute_check_operating_condition_tool",
    "execute_recommend_next_experiment_tool",
    "execute_retrieve_battery_evidence_tool",
    "execute_scenario_lifetime_tool",
    "execute_validate_battery_data_tool",
    "load_optional_mcp_sdk",
    "register_adapt_to_target_domain_tool",
    "register_audit_dataset_split_tool",
    "register_batch_decision_tool",
    "register_check_operating_condition_tool",
    "register_recommend_next_experiment_tool",
    "register_retrieve_battery_evidence_tool",
    "register_scenario_lifetime_tool",
    "register_validate_battery_data_tool",
    "run_mcp_host",
]
