"""Shared typed tool registry with lazy optional-domain exports."""

from __future__ import annotations

from importlib import import_module
from typing import Any

from quanxin_life.tools.registry import (
    DuplicateToolError,
    RegisteredTool,
    StandardToolName,
    ToolAuthorizationError,
    ToolContractError,
    ToolDefinition,
    ToolExecutionError,
    ToolExecutionScope,
    ToolInputValidationError,
    ToolRegistry,
    ToolRegistryError,
    ToolSchema,
    UnknownToolError,
)

_EXPORT_MODULES = {
    "AdaptToTargetDomainToolInput": "target_domain_adaptation",
    "AuditDatasetSplitToolInput": "split_audit",
    "BATCH_DECISION_TOOL_VERSION": "batch_decision",
    "BATTERY_EVIDENCE_ARTIFACT_TYPE": "battery_evidence",
    "BATTERY_EVIDENCE_RETRIEVAL_TOOL_VERSION": "battery_evidence",
    "BatchDecisionToolInput": "batch_decision",
    "CheckOperatingConditionToolInput": "physics_check",
    "CompareOperationScenariosToolInput": "blast_scenarios",
    "COMPARE_OPERATION_SCENARIOS_ARTIFACT_TYPE": "blast_scenarios",
    "COMPARE_OPERATION_SCENARIOS_TOOL_VERSION": "blast_scenarios",
    "DATA_QUALITY_MODEL_VERSION": "data_quality",
    "DATA_QUALITY_TOOL_VERSION": "data_quality",
    "EXPERIMENT_RECOMMENDATION_EVIDENCE_TYPE": "next_experiment_recommendation",
    "McpAdapterError": "mcp_adapter",
    "McpHost": "mcp_host",
    "McpHostConfig": "mcp_host",
    "McpRequestValidationError": "mcp_adapter",
    "McpSdkUnavailableError": "mcp_adapter",
    "McpToolAdapter": "mcp_adapter",
    "McpToolCallRequest": "mcp_adapter",
    "McpTransport": "mcp_host",
    "NEXT_EXPERIMENT_RECOMMENDATION_TOOL_VERSION": "next_experiment_recommendation",
    "PHYSICS_CHECK_TOOL_VERSION": "physics_check",
    "PROJECT_STORAGE_LIFETIME_ARTIFACT_TYPE": "blast_scenarios",
    "PROJECT_STORAGE_LIFETIME_TOOL_VERSION": "blast_scenarios",
    "ProjectStorageLifetimeToolInput": "blast_scenarios",
    "RecommendNextExperimentToolInput": "next_experiment_recommendation",
    "RetrieveBatteryEvidenceToolInput": "battery_evidence",
    "SCENARIO_CONVERSION_WARNING": "scenario_lifetime",
    "SCENARIO_LIFETIME_ARTIFACT_TYPE": "scenario_lifetime",
    "SCENARIO_LIFETIME_TOOL_VERSION": "scenario_lifetime",
    "SPLIT_AUDIT_MODEL_VERSION": "split_audit",
    "SPLIT_AUDIT_TOOL_VERSION": "split_audit",
    "ScenarioLifetimeToolInput": "scenario_lifetime",
    "TARGET_DOMAIN_ADAPTATION_TOOL_VERSION": "target_domain_adaptation",
    "ValidateBatteryDataToolInput": "data_quality",
    "create_available_tool_registry": "bootstrap",
    "create_mcp_host": "mcp_host",
    "execute_adapt_to_target_domain_tool": "target_domain_adaptation",
    "execute_audit_dataset_split_tool": "split_audit",
    "execute_batch_decision_tool": "batch_decision",
    "execute_check_operating_condition_tool": "physics_check",
    "execute_compare_operation_scenarios_tool": "blast_scenarios",
    "execute_project_storage_lifetime_tool": "blast_scenarios",
    "execute_recommend_next_experiment_tool": "next_experiment_recommendation",
    "execute_retrieve_battery_evidence_tool": "battery_evidence",
    "execute_scenario_lifetime_tool": "scenario_lifetime",
    "execute_validate_battery_data_tool": "data_quality",
    "load_optional_mcp_sdk": "mcp_adapter",
    "register_adapt_to_target_domain_tool": "target_domain_adaptation",
    "register_audit_dataset_split_tool": "split_audit",
    "register_batch_decision_tool": "batch_decision",
    "register_check_operating_condition_tool": "physics_check",
    "register_compare_operation_scenarios_tool": "blast_scenarios",
    "register_project_storage_lifetime_tool": "blast_scenarios",
    "register_recommend_next_experiment_tool": "next_experiment_recommendation",
    "register_retrieve_battery_evidence_tool": "battery_evidence",
    "register_scenario_lifetime_tool": "scenario_lifetime",
    "register_validate_battery_data_tool": "data_quality",
    "run_mcp_host": "mcp_host",
}

__all__ = [
    "BATCH_DECISION_TOOL_VERSION",
    "BATTERY_EVIDENCE_ARTIFACT_TYPE",
    "BATTERY_EVIDENCE_RETRIEVAL_TOOL_VERSION",
    "COMPARE_OPERATION_SCENARIOS_ARTIFACT_TYPE",
    "COMPARE_OPERATION_SCENARIOS_TOOL_VERSION",
    "DATA_QUALITY_MODEL_VERSION",
    "DATA_QUALITY_TOOL_VERSION",
    "EXPERIMENT_RECOMMENDATION_EVIDENCE_TYPE",
    "NEXT_EXPERIMENT_RECOMMENDATION_TOOL_VERSION",
    "PHYSICS_CHECK_TOOL_VERSION",
    "PROJECT_STORAGE_LIFETIME_ARTIFACT_TYPE",
    "PROJECT_STORAGE_LIFETIME_TOOL_VERSION",
    "SCENARIO_CONVERSION_WARNING",
    "SCENARIO_LIFETIME_ARTIFACT_TYPE",
    "SCENARIO_LIFETIME_TOOL_VERSION",
    "SPLIT_AUDIT_MODEL_VERSION",
    "SPLIT_AUDIT_TOOL_VERSION",
    "TARGET_DOMAIN_ADAPTATION_TOOL_VERSION",
    "AdaptToTargetDomainToolInput",
    "AuditDatasetSplitToolInput",
    "BatchDecisionToolInput",
    "CheckOperatingConditionToolInput",
    "CompareOperationScenariosToolInput",
    "DuplicateToolError",
    "McpAdapterError",
    "McpHost",
    "McpHostConfig",
    "McpRequestValidationError",
    "McpSdkUnavailableError",
    "McpToolAdapter",
    "McpToolCallRequest",
    "McpTransport",
    "ProjectStorageLifetimeToolInput",
    "RecommendNextExperimentToolInput",
    "RegisteredTool",
    "RetrieveBatteryEvidenceToolInput",
    "ScenarioLifetimeToolInput",
    "StandardToolName",
    "ToolAuthorizationError",
    "ToolContractError",
    "ToolDefinition",
    "ToolExecutionError",
    "ToolExecutionScope",
    "ToolInputValidationError",
    "ToolRegistry",
    "ToolRegistryError",
    "ToolSchema",
    "UnknownToolError",
    "ValidateBatteryDataToolInput",
    "create_available_tool_registry",
    "create_mcp_host",
    "execute_adapt_to_target_domain_tool",
    "execute_audit_dataset_split_tool",
    "execute_batch_decision_tool",
    "execute_check_operating_condition_tool",
    "execute_compare_operation_scenarios_tool",
    "execute_project_storage_lifetime_tool",
    "execute_recommend_next_experiment_tool",
    "execute_retrieve_battery_evidence_tool",
    "execute_scenario_lifetime_tool",
    "execute_validate_battery_data_tool",
    "load_optional_mcp_sdk",
    "register_adapt_to_target_domain_tool",
    "register_audit_dataset_split_tool",
    "register_batch_decision_tool",
    "register_check_operating_condition_tool",
    "register_compare_operation_scenarios_tool",
    "register_project_storage_lifetime_tool",
    "register_recommend_next_experiment_tool",
    "register_retrieve_battery_evidence_tool",
    "register_scenario_lifetime_tool",
    "register_validate_battery_data_tool",
    "run_mcp_host",
]


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(f"{__name__}.{module_name}"), name)
    globals()[name] = value
    return value
